development:
  database: leanms_dabatase_package_development
  hostname: 
  port: 5432
  user: postgres
  password: 

test:
  database: leanms_dabatase_package_test
  hostname: localhost
  port: 5432
  user: postgres
  password:    

production:
  database: leanms_dabatase_package_production
  hostname: localhost
  port: 5432
  user: postgres
  password: 