name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build && Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Postgres
      uses: huaxk/postgis-action@v1
      with:
        postgresql password: ''
        postgresql user: 'postgres'  

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .

    - name: Test Coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: e499967cb9d43de66b7403241db0be08316cd8d50403e309cef2c3d49c9b1833
      with:
        coverageCommand: go test -coverprofile c.out -v ./...
        coverageLocations: ${{github.workspace}}/c.out:gocov
        prefix: github.com/lean-ms/database